debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.before.prac: debug
    org.org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace



spring:
  datasource:

    url: jdbc:mysql://localhost:3306
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated

cloud:
  aws:
    s3:
      bucket: your-bucket-name
    region:
      static: ap-northeast-2
    credentials:
      access-key: YOUR_AWS_ACCESS_KEY
      secret-key: YOUR_AWS_SECRET_KEY